name: Trigger Render Deploy for Production

# This workflow only triggers a deploy on Render. Render will handle all builds and deployment steps.

on:
  release:
    types: [published]

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Production deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_PROD }}" 