name: Trigger Render Deploy for QA

# This workflow only triggers a deploy on Render. Render will handle all builds and deployment steps.

on:
  push:
    branches:
      - main

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render QA deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_QA }}" 